services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.5
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: http://localhost:9090
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro
      - ./keycloak-theme/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    command:
      - start-dev

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      # - "5672:5672" # Internal communication port
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - backend

  transcoder:
    image: transcoder-worker
    build:
      context: ./transcoder
      dockerfile: Dockerfile
    container_name: transcoder-worker
    depends_on:
      - rabbitmq
    networks:
      - backend
    volumes:
      - uploads:${UPLOAD_DIR}

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # ports:
    #   - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MULTIPART_MAX_FILE_SIZE: ${SPRING_MULTIPART_MAX_FILE_SIZE}
      SPRING_MULTIPART_MAX_REQUEST_SIZE: ${SPRING_MULTIPART_MAX_REQUEST_SIZE}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - keycloak
      - rabbitmq
    networks:
      - backend
    volumes:
      - uploads:${UPLOAD_DIR}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${API_BASE_URL}
        VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL}
        VITE_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        VITE_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    environment:
      NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - backend

volumes:
  keycloak_data:
  postgres_data:
  uploads:

networks:
  backend:
